### PR TITLE
fix: add env checks before attempting to run project code

### LINKED ISSUE #72: imperfect error messages if user ignores "start a new terminal session"
If the user does a setup and ignores the instructions to "start a new terminal session" and jumps directly to "run" the error message is misleading:

```
$ xs-dev setup
✔ Moddable SDK successfully set up! Start a new terminal session and run the "helloworld example": xs-dev run --example helloworld
$ xs-dev run --example helloworld
Example project does not exist.
Lookup the available examples: xs-dev run --list-examples
$ xs-dev run --list-examples
/opt/homebrew/lib/node_modules/xs-dev/node_modules/gluegun/build/index.js:15
    throw up;
    ^

Error: At least one choice must be selectable
```

xs-dev might want to have some preflight checks that it uses consistently to determine if the install is good (for the Moddable SDK itself, and for each device target). This will never be perfect, but some are pretty straightforward - like a missing $MODDABLE environment variable.

Here's an example from the another perspective. The user does a teardown and then tries to use the install:

```
$ xs-dev teardown
$ xs-dev run --example piu/balls
Example project does not exist.
Lookup the available examples: xs-dev run --list-examples
```

### LINKED ISSUE #78: Pico build on macOS fails because pioasm missing
After install Pico support on macOS Monterey (12.3.1) building helloworld...

```
xs-dev run --example helloworld --device pico
```

...fails because `pioasm` can't be found.

<details>

```
$ xs-dev run --example helloworld --device pico
⠧ Building and deploying project /Users/peterhoddie/.local/share/moddable/examples/helloworld on pico/usr/local/lib/node_modules/xs-dev/node_modules/gluegun/build/index.js:15
    throw up;
    ^

Error: Command failed with exit code 2: mcconfig -m -p pico -t all -o /Users/peterhoddie/.local/share/moddable/build -d
make: /Users/peterhoddie/pico/pico-sdk/build/pioasm/pioasm: No such file or directory
make: *** [/Users/peterhoddie/.local/share/moddable/build/tmp/pico/debug/helloworld/ws2812.pio.h] Error 1
make: *** Waiting for unfinished jobs....
/Users/peterhoddie/.local/share/moddable/xs/platforms/pico/xsPlatform.c: In function 'fxCreateMachinePlatform':
/Users/peterhoddie/.local/share/moddable/xs/platforms/pico/xsPlatform.c:79:2: warning: implicit declaration of function 'modMachineTaskInit' [-Wimplicit-function-declaration]
   79 |  modMachineTaskInit(the);
      |  ^~~~~~~~~~~~~~~~~~
/Users/peterhoddie/.local/share/moddable/xs/platforms/mc/xsHosts.c: In function 'modRunMachineSetup':
/Users/peterhoddie/.local/share/moddable/xs/platforms/mc/xsHosts.c:559:2: warning: implicit declaration of function 'modInstrumentationSetup'; did you mean 'modInstrumentationSet_'? [-Wimplicit-function-declaration]
  559 |  modInstrumentationSetup(the);
      |  ^~~~~~~~~~~~~~~~~~~~~~~
      |  modInstrumentationSet_
/Users/peterhoddie/.local/share/moddable/xs/platforms/pico/xsPlatform.c: In function 'fxDeleteMachinePlatform':
/Users/peterhoddie/.local/share/moddable/xs/platforms/pico/xsPlatform.c:103:2: warning: implicit declaration of function 'modMachineTaskUninit' [-Wimplicit-function-declaration]
  103 |  modMachineTaskUninit(the);
      |  ^~~~~~~~~~~~~~~~~~~~
/Users/peterhoddie/.local/share/moddable/xs/platforms/pico/xsPlatform.c: In function 'fxReceiveLoop':
/Users/peterhoddie/.local/share/moddable/xs/platforms/pico/xsPlatform.c:462:6: warning: implicit declaration of function 'modMessagePostToMachine' [-Wimplicit-function-declaration]
  462 |      modMessagePostToMachine(current, NULL, 0xffff, doDebugCommand, current);
      |      ^~~~~~~~~~~~~~~~~~~~~~~
/Users/peterhoddie/.local/share/moddable/xs/platforms/pico/xsPlatform.c: In function 'fxInNetworkDebugLoop':
/Users/peterhoddie/.local/share/moddable/xs/platforms/pico/xsPlatform.c:723:66: warning: comparison between pointer and integer
  723 |  return the->DEBUG_LOOP && the->connection && (kSerialConnection != the->connection);
      |                                                                  ^~
/var/folders/nd/2xq97b3j4fgd9zqrz1hlykvm0000gn/T//ccxgp5iL.s: Assembler messages:
/var/folders/nd/2xq97b3j4fgd9zqrz1hlykvm0000gn/T//ccxgp5iL.s:457: Warning: setting incorrect section attributes for .data.xsram
/var/folders/nd/2xq97b3j4fgd9zqrz1hlykvm0000gn/T//ccC4rD4c.s: Assembler messages:
/var/folders/nd/2xq97b3j4fgd9zqrz1hlykvm0000gn/T//ccC4rD4c.s:2846: Warning: setting incorrect section attributes for .rodata
# compile pio:  ws2812.pio
# library xs: xsHosts.c
# library xs: xsHost.c
# library xs: xsPlatform.c
# library xs: xsAll.c
    at makeError (/usr/local/lib/node_modules/xs-dev/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/usr/local/lib/node_modules/xs-dev/node_modules/execa/index.js:118:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  shortMessage: 'Command failed with exit code 2: mcconfig -m -p pico -t all -o /Users/peterhoddie/.local/share/moddable/build -d',
  command: 'mcconfig -m -p pico -t all -o /Users/peterhoddie/.local/share/moddable/build -d',
  escapedCommand: 'mcconfig -m -p pico -t all -o "/Users/peterhoddie/.local/share/moddable/build" -d',
  exitCode: 2,
  signal: undefined,
  signalDescription: undefined,
  stdout: '# compile pio:  ws2812.pio\n' +
    '# library xs: xsHosts.c\n' +
    '# library xs: xsHost.c\n' +
    '# library xs: xsPlatform.c\n' +
    '# library xs: xsAll.c',
  stderr: 'make: /Users/peterhoddie/pico/pico-sdk/build/pioasm/pioasm: No such file or directory\n' +
    'make: *** [/Users/peterhoddie/.local/share/moddable/build/tmp/pico/debug/helloworld/ws2812.pio.h] Error 1\n' +
    'make: *** Waiting for unfinished jobs....\n' +
    "/Users/peterhoddie/.local/share/moddable/xs/platforms/pico/xsPlatform.c: In function 'fxCreateMachinePlatform':\n" +
    "/Users/peterhoddie/.local/share/moddable/xs/platforms/pico/xsPlatform.c:79:2: warning: implicit declaration of function 'modMachineTaskInit' [-Wimplicit-function-declaration]\n" +
    '   79 |  modMachineTaskInit(the);\n' +
    '      |  ^~~~~~~~~~~~~~~~~~\n' +
    "/Users/peterhoddie/.local/share/moddable/xs/platforms/mc/xsHosts.c: In function 'modRunMachineSetup':\n" +
    "/Users/peterhoddie/.local/share/moddable/xs/platforms/mc/xsHosts.c:559:2: warning: implicit declaration of function 'modInstrumentationSetup'; did you mean 'modInstrumentationSet_'? [-Wimplicit-function-declaration]\n" +
    '  559 |  modInstrumentationSetup(the);\n' +
    '      |  ^~~~~~~~~~~~~~~~~~~~~~~\n' +
    '      |  modInstrumentationSet_\n' +
    "/Users/peterhoddie/.local/share/moddable/xs/platforms/pico/xsPlatform.c: In function 'fxDeleteMachinePlatform':\n" +
    "/Users/peterhoddie/.local/share/moddable/xs/platforms/pico/xsPlatform.c:103:2: warning: implicit declaration of function 'modMachineTaskUninit' [-Wimplicit-function-declaration]\n" +
    '  103 |  modMachineTaskUninit(the);\n' +
    '      |  ^~~~~~~~~~~~~~~~~~~~\n' +
    "/Users/peterhoddie/.local/share/moddable/xs/platforms/pico/xsPlatform.c: In function 'fxReceiveLoop':\n" +
    "/Users/peterhoddie/.local/share/moddable/xs/platforms/pico/xsPlatform.c:462:6: warning: implicit declaration of function 'modMessagePostToMachine' [-Wimplicit-function-declaration]\n" +
    '  462 |      modMessagePostToMachine(current, NULL, 0xffff, doDebugCommand, current);\n' +
    '      |      ^~~~~~~~~~~~~~~~~~~~~~~\n' +
    "/Users/peterhoddie/.local/share/moddable/xs/platforms/pico/xsPlatform.c: In function 'fxInNetworkDebugLoop':\n" +
    '/Users/peterhoddie/.local/share/moddable/xs/platforms/pico/xsPlatform.c:723:66: warning: comparison between pointer and integer\n' +
    '  723 |  return the->DEBUG_LOOP && the->connection && (kSerialConnection != the->connection);\n' +
    '      |                                                                  ^~\n' +
    '/var/folders/nd/2xq97b3j4fgd9zqrz1hlykvm0000gn/T//ccxgp5iL.s: Assembler messages:\n' +
    '/var/folders/nd/2xq97b3j4fgd9zqrz1hlykvm0000gn/T//ccxgp5iL.s:457: Warning: setting incorrect section attributes for .data.xsram\n' +
    '/var/folders/nd/2xq97b3j4fgd9zqrz1hlykvm0000gn/T//ccC4rD4c.s: Assembler messages:\n' +
    '/var/folders/nd/2xq97b3j4fgd9zqrz1hlykvm0000gn/T//ccC4rD4c.s:2846: Warning: setting incorrect section attributes for .rodata',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}

Node.js v18.12.1
```

</details>

It may be that the Pico setup code in xs-dev needs to be updated. The dependency on `pioasm` is relatively new, arriving when Pico W platform support was implemented. @mkellner maybe able to provide some information to help with this.

### LINKED ISSUE #79: Attempting ESP32 build without esp32 set-up fails confusingly
After a set-up of the Moddable SDK on macOS, but without having set-up the ESP32 tools, the failure message isn't helpful in guiding the user to the solution.

```
$ xs-dev run --example helloworld --device=esp32
⠸ Building and deploying project ~/.local/share/moddable/examples/helloworld on esp32

/opt/homebrew/lib/node_modules/xs-dev/node_modules/gluegun/build/index.js:15
    throw up;
    ^

Error: Command failed with exit code 2: mcconfig -m -p esp32 -t all -o ~/.local/share/moddable/build -d
fatal: not a git repository (or any of the parent directories): .git
~/.local/share/moddable/build/tmp/esp32/debug/helloworld/makefile:152: Could not detect ESP-IDF version.
```

### PR DESCRIPTION
**Pull request by HipsterBrown**
Fixes #78 
Fixes #79 
Fixes #72

### CODE REVIEW

File: src/extensions/setup-extension.ts [hunk 1]
```diff
@@ -10,8 +10,11 @@ import setupPico from '../toolbox/setup/pico'
 export default async (toolbox: XSDevToolbox): Promise<void> => {
   toolbox.setup = {
     darwin: setupMac,
+    mac: setupMac,
```
Comment (HipsterBrown) [inline src/extensions/setup-extension.ts:13]: Updating these list to have 1-to-1 matches for the platform target.

File: src/toolbox/build/index.ts [hunk 2]
```diff
@@ -84,6 +97,34 @@ export async function build({
     }
   }
 
+  if (targetPlatform !== '') {
```
Comment (HipsterBrown) [inline src/toolbox/build/index.ts:100]: This might eventually be refactored into more organized modules, but keeping the explicit approach here for now

File: src/toolbox/setup/esp8266.ts [hunk 3]
```diff
@@ -35,24 +37,25 @@ export default async function (): Promise<void> {
   // 0. ensure Moddable exists
   if (!moddableExists()) {
     spinner.fail(
-      'Moddable tooling required. Run `xs-dev setup` before trying again.'
+      `Moddable tooling required. Run 'xs-dev setup --device ${DEVICE_ALIAS[OS]}' before trying again.`
```
Comment (HipsterBrown) [inline src/toolbox/setup/esp8266.ts:40]: A nice follow up to these messages could be a prompt to automatically run the setup command for the user.

File: src/toolbox/setup/esp8266/mac.ts [hunk 4]
```diff
@@ -6,8 +6,15 @@ export async function installDeps(
 ): Promise<void> {
   if (system.which('python') === null) {
     spinner.start('Installing python from homebrew')
-    await system.exec('brew install python')
-    spinner.succeed()
+    try {
+      await system.exec('brew install python')
+      spinner.succeed()
+    } catch (error: unknown) {
+      if (error instanceof Error && error.toString().includes('xcode-select')) {
```
Comment (HipsterBrown) [inline src/toolbox/setup/esp8266/mac.ts:13]: I ran into this locally during testing and wanted a better error message than the default stack trace. This has motivated some research into more robust error handling overall, rather than one-off handling / messaging.

File: src/toolbox/setup/esp8266.ts (hunk 3 above)
Comment (phoddie) [reply src/toolbox/setup/esp8266.ts:40]: I've definitely seen that developer just want to get started with their MCU. It would fit their thinking if they could just do set-up for ESP32, Pico, etc and that would make sure that the core Moddable SDK set-up is taken care of if needed.
