### PR TITLE
fix: ensure homebrew is available before running install commands

### LINKED ISSUE #77: ESP32 install fails on macOS if brew not installed
More testing on a (nearly) fresh install of macOS (Monterey, 12.3.1). If `brew` isn't installed, the ESP32 install fails when it tries to `brew install python`. At a minimum, it should probably display a more proactive error message so the user knows what to do.

<details>

```
$ xs-dev setup --device=esp32  
ℹ Ensuring esp32 install directory
✔ Cloning esp-idf repo
⠋ Installing build dependencies/usr/local/lib/node_modules/xs-dev/node_modules/gluegun/build/index.js:15
    throw up;
    ^

Error: Command failed with ENOENT: brew install python
spawn brew ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:476:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn brew',
  path: 'brew',
  spawnargs: [ 'install', 'python' ],
  originalMessage: 'spawn brew ENOENT',
  shortMessage: 'Command failed with ENOENT: brew install python\nspawn brew ENOENT',
  command: 'brew install python',
  escapedCommand: 'brew install python',
  exitCode: undefined,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: '',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}

Node.js v18.12.1

```

</details>

After [installing Homebrew](https://brew.sh),  re-running `xs-dev setup --device=esp32` succeeds.

### PR DESCRIPTION
**Pull request by HipsterBrown**
Fixes #77 

----

The currently error handling for ensuring Homebrew is available suggests users to visit https://brew.sh/ and follow the instructions there. This is another prompt that can handle this task automatically if the user chooses.

### CODE REVIEW

File: src/toolbox/setup/esp32.ts [hunk 1]
```diff
@@ -39,7 +39,7 @@ export default async function(): Promise<void> {
   if (filesystem.exists(IDF_PATH) === false) {
     spinner.start('Cloning esp-idf repo')
     await system.spawn(
-      `git clone -b ${ESP_BRANCH} --recursive ${ESP_IDF_REPO} ${IDF_PATH}`
+      `git clone --depth 1 --single-branch -b ${ESP_BRANCH} --recursive ${ESP_IDF_REPO} ${IDF_PATH}`
```
Comment (HipsterBrown) [inline src/toolbox/setup/esp32.ts:42]: Standardizing on shallow cloning git repos used as dependencies.
