### PR TITLE
fix: ensure file exists before upsert

### LINKED ISSUE #17: fix: ensure xs-dev-export.sh exists before allowing upserts
While it is not very likely that users will run commands that rely on `xs-dev-exports.sh` existing before upserting config into it, since it is created during the default `setup` command, it would be safer to ensure the file exists before any potential write.

This could be done similar to the `moddableExists` check, at the top of any `setup` module. Or have it abstracted away through an `updateExports` helper that wraps the `upsert` helper and ensures the file exists, which would probably be more maintainable for new folks contributing to the codebase.

### PR DESCRIPTION
**Pull request by HipsterBrown**
Fixes #17

### CODE REVIEW

File: src/toolbox/setup/wasm.ts [hunk 1]
```diff
@@ -25,16 +25,24 @@ export default async function (): Promise<void> {
...
     spinner.start('Cloning emsdk repo')
     await system.spawn(`git clone ${EMSDK_REPO} ${EMSDK_PATH}`)
     spinner.succeed()
   }
-  if (process.env.EMSDK === undefined) {
+
+  if (
+    process.env.EMSDK === undefined ||
+    filesystem.exists(process.env.EMSDK) !== 'dir'
+  ) {
```
Comment (HipsterBrown) [inline src/toolbox/setup/wasm.ts:39]: Also addressing an issue when tearing down and setting up in the same shell session.
